database:
    driver: pdo_mysql
    host: 127.0.0.1
    port: null
    name: colombia
    user: colombia
    password: rockbus
    charset: 'utf8'

payments:
    CreditCard: [PayuLatam]

PayuLatam:
    transaction_url: http://stg.api.payulatam.com/payments-api/4.0/service.cgi
    reports_url: https://stg.api.payulatam.com/reports-api/4.0/service.cgi
    api_key: 6u39nqhq8ftd0hlvnjfs66eh8c
    api_login: 11959c415b33d0c
    merchant_id: 500238
    account_id: 500538
    tx_value: 3
    currency: USD
    response_url: http://www.api.dev/
    language: en
    test: true

booking_engines: [CbConnect, RapidoOchoa]

CbConnect:
    host: http://33.33.33.94

RapidoOchoa:
    departure_url: http://190.85.56.76/wsTarifasROpruebas/ServicioTarifas.asmx
    departure_wsdl: http://190.85.56.76/wsTarifasROpruebas/ServicioTarifas.asmx?wsdl
    arrival_url: http://190.145.82.98/SATServicesclickbus/Service/WSVentaOnline.svc
    arrival_wsdl: http://190.145.82.98/SATServicesclickbus/Service/WSVentaOnline.svc/basic?wsdl
    user: MVM
    password: Mvm2007mvm!
    locale: es_CO
    place_country: COL
    bus_company_name: RapidoOchoa

# payment:
#     payu_latam:
#         payment: https://stg.api.payulatam.com/payments-api/4.0/service.cgi
#         consultation: https://stg.api.payulatam.com/reports-api/4.0/service.cgi

